In [1]:
from sklearn.datasets import make_friedman1

In [9]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [10]:
data,target=make_friedman1(n_samples=10, n_features=10,random_state=0)

In [11]:
target

array([17.2134918 , 19.37965436, 14.75030901, 11.81662128,  9.45520588,
       13.90806032,  3.40447398, 24.20228984, 17.5783377 , 17.51556532])

In [13]:
model=SVR(kernel='linear')
#definng rfe
#model tell whta type of estimator it is
#5 is no. of features you want to keep finally
# step=1 : at each step how many features you want to remove at each step. floating point means percentage of feature you want ot remove at each step
rfe=RFE(model,5,step=1)

In [14]:
rfe=rfe.fit(data,target)

In [16]:
#to see the ranking for all the features
#note: to find an intrinsic qualit of a model use _
rfe.ranking_

array([1, 5, 1, 1, 1, 1, 2, 6, 4, 3])

In [17]:
# to see estimator
rfe.estimator_


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
# masking give true to best feature. You can multiply this to your dataset directly for him to select good features 
rfe.support_

array([ True, False,  True,  True,  True,  True, False, False, False,
       False])

In [24]:
data,target=make_friedman1(n_samples=50, n_features=10,random_state=0)
import pandas as pd
data=pd.DataFrame(data)

In [25]:
import numpy as np
# which features are false so that we can drop
print(np.where(rfe.support_==False)[0])

[1 6 7 8 9]


In [29]:
data1=data.drop(data.columns[np.where(rfe.support_==False)[0]],axis=1)

In [30]:
model.fit(data1,target)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
model.score(data1,target)

0.5677446397642008